import { createClient } from "jsr:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://ai-clo-ptithcm.github.io','https://apmaths.github.io']);
const roles=new Set(['admin','exam_officer','teacher','proctor']);
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=ORIGINS.has(o)||o.startsWith('http://localhost:')||o.startsWith('http://127.0.0.1:');return {'Access-Control-Allow-Origin':ok?o:'https://ai-clo-ptithcm.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(req)});}
function password(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$';const a=new Uint8Array(14);crypto.getRandomValues(a);return [...a].map(x=>chars[x%chars.length]).join('');}
async function admin(req:Request){const jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)throw Object.assign(new Error('Chưa đăng nhập.'),{status:401});const u=await db.auth.getUser(jwt);if(u.error||!u.data.user)throw Object.assign(new Error('Phiên đăng nhập không hợp lệ.'),{status:401});const p=await db.from('profiles').select('*').eq('id',u.data.user.id).maybeSingle();if(p.error)throw p.error;if(!p.data?.active||p.data.system_role!=='admin')throw Object.assign(new Error('Chỉ Admin hệ thống được quản lý tài khoản.'),{status:403});return {user:u.data.user,profile:p.data};}
async function log(actorId:string,action:string,userId:string,payload:any){await db.from('audit_logs').insert({actor_user_id:actorId,action,entity_type:'profile',entity_id:userId,payload});}
async function protectLastAdmin(targetId:string,newRole:string,newActive:boolean){const target=await db.from('profiles').select('system_role,active').eq('id',targetId).single();if(target.error)throw target.error;if(target.data.system_role==='admin'&&target.data.active&&(newRole!=='admin'||!newActive)){const c=await db.from('profiles').select('id',{count:'exact',head:true}).eq('system_role','admin').eq('active',true);if((c.count||0)<=1)throw Object.assign(new Error('Không thể vô hiệu hóa hoặc hạ quyền Admin hoạt động cuối cùng.'),{status:409});}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,{error:'Method not allowed'},405);try{const a=await admin(req),b=await req.json().catch(()=>({})),action=String(b.action||'');if(action==='create'){const email=String(b.email||'').trim().toLowerCase(),fullName=String(b.fullName||'').trim(),role=String(b.role||'teacher');if(!email||!fullName||!roles.has(role))return out(req,{error:'Thông tin tài khoản không hợp lệ.'},400);const temp=password();const r=await db.auth.admin.createUser({email,password:temp,email_confirm:true,user_metadata:{full_name:fullName}});if(r.error)throw r.error;const up=await db.from('profiles').update({email,full_name:fullName,system_role:role,active:true}).eq('id',r.data.user.id);if(up.error)throw up.error;await log(a.user.id,'staff_create',r.data.user.id,{email,role});return out(req,{ok:true,userId:r.data.user.id,email,temporaryPassword:temp});}if(action==='update'){const userId=String(b.userId||''),role=String(b.role||''),active=Boolean(b.active);if(!userId||!roles.has(role))return out(req,{error:'Dữ liệu không hợp lệ.'},400);await protectLastAdmin(userId,role,active);const r=await db.from('profiles').update({system_role:role,active}).eq('id',userId).select().single();if(r.error)throw r.error;await log(a.user.id,'staff_update',userId,{role,active});return out(req,{ok:true,profile:r.data});}if(action==='reset-password'){const userId=String(b.userId||'');const temp=password();const r=await db.auth.admin.updateUserById(userId,{password:temp});if(r.error)throw r.error;await log(a.user.id,'staff_password_reset',userId,{});return out(req,{ok:true,temporaryPassword:temp});}return out(req,{error:'Action không hợp lệ.'},400);}catch(e){console.error(e);const s=Number((e as any)?.status||500);return out(req,{error:s>=500?'Máy chủ đang gặp lỗi.':String((e as any)?.message||'Có lỗi xảy ra.')},s);}});
