import { createClient } from "jsr:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://ai-clo-ptithcm.github.io','https://apmaths.github.io']);
const TRANSITIONS:Record<string,Set<string>>={draft:new Set(['ready']),ready:new Set(['draft','live']),live:new Set(['closed']),closed:new Set(['archived']),archived:new Set()};
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=ORIGINS.has(o)||o.startsWith('http://localhost:')||o.startsWith('http://127.0.0.1:');return {'Access-Control-Allow-Origin':ok?o:'https://ai-clo-ptithcm.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(req)});}
async function actor(req:Request){const jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)throw Object.assign(new Error('Chưa đăng nhập.'),{status:401});const u=await db.auth.getUser(jwt);if(u.error||!u.data.user)throw Object.assign(new Error('Phiên đăng nhập không hợp lệ.'),{status:401});const p=await db.from('profiles').select('*').eq('id',u.data.user.id).maybeSingle();if(p.error)throw p.error;if(!p.data?.active)throw Object.assign(new Error('Tài khoản chưa được kích hoạt.'),{status:403});return {user:u.data.user,profile:p.data};}
async function canManage(a:any,examId:string){if(a.profile.system_role==='admin')return true;const m=await db.from('exam_members').select('exam_role,permissions').eq('exam_id',examId).eq('user_id',a.user.id).maybeSingle();if(m.error)throw m.error;return !!m.data&&(m.data.exam_role==='owner'||(m.data.permissions||[]).includes('manage_exam'));}
async function readiness(examId:string){const errors:string[]=[];const sr=await db.from('exam_sessions').select('id,name').eq('exam_id',examId);if(sr.error)throw sr.error;const sessions=sr.data||[];if(!sessions.length)errors.push('Kỳ thi chưa có ca thi.');const students=await db.from('exam_students').select('id').eq('exam_id',examId).eq('active',true);if(students.error)throw students.error;if(!students.data?.length)errors.push('Kỳ thi chưa có sinh viên.');if(students.data?.length){const codes=await db.from('exam_student_codes').select('exam_student_id').in('exam_student_id',students.data.map(x=>x.id));if(codes.error)throw codes.error;if((codes.data||[]).length!==students.data.length)errors.push('Còn sinh viên chưa có mã thi.');}
  for(const s of sessions){const rooms=await db.from('exam_rooms').select('id').eq('session_id',s.id);if(rooms.error)throw rooms.error;if(!rooms.data?.length)errors.push(`${s.name}: chưa có phòng thi.`);const p=await db.from('exam_papers').select('id').eq('session_id',s.id).maybeSingle();if(p.error)throw p.error;if(!p.data){errors.push(`${s.name}: chưa có đề thi.`);continue;}const v=await db.from('exam_paper_versions').select('id').eq('paper_id',p.data.id).in('status',['locked','hotfix']).order('version_no',{ascending:false}).limit(1).maybeSingle();if(v.error)throw v.error;if(!v.data){errors.push(`${s.name}: đề chưa khóa.`);continue;}const q=await db.from('paper_version_questions').select('id',{count:'exact',head:true}).eq('paper_version_id',v.data.id);if(q.error)throw q.error;if(!(q.count||0))errors.push(`${s.name}: đề chưa có câu hỏi.`);}
  return errors;
}
async function audit(userId:string,examId:string,from:string,to:string,payload:any={}){await db.from('audit_logs').insert({actor_user_id:userId,exam_id:examId,action:'exam_status_changed',entity_type:'exam',entity_id:examId,payload:{from,to,...payload}});}
async function setStatus(req:Request,b:any){const examId=String(b.examId||''),target=String(b.status||'');const a=await actor(req);if(!await canManage(a,examId))return out(req,{error:'Bạn không có quyền đổi trạng thái kỳ thi.'},403);const er=await db.from('exams').select('*').eq('id',examId).single();if(er.error)throw er.error;const exam=er.data,current=String(exam.status);if(current===target)return out(req,{ok:true,exam});if(!TRANSITIONS[current]?.has(target))return out(req,{error:`Không thể chuyển trực tiếp từ ${current} sang ${target}.`},409);
  if(['ready','live'].includes(target)){const errors=await readiness(examId);if(errors.length)return out(req,{error:'Kỳ thi chưa đạt điều kiện sẵn sàng.',readinessErrors:errors},409);}
  if(target==='draft'){const sessions=await db.from('exam_sessions').select('id').eq('exam_id',examId);if(sessions.error)throw sessions.error;const ids=(sessions.data||[]).map(x=>x.id);if(ids.length){const at=await db.from('exam_attempts').select('id',{count:'exact',head:true}).in('session_id',ids);if(at.error)throw at.error;if(at.count)return out(req,{error:'Đã có lượt thi được tạo; không thể đưa kỳ thi về Nháp.'},409);}}
  if(target==='closed'){const sessions=await db.from('exam_sessions').select('id').eq('exam_id',examId);if(sessions.error)throw sessions.error;const ids=(sessions.data||[]).map(x=>x.id);if(ids.length){const active=await db.from('exam_attempts').select('id',{count:'exact',head:true}).in('session_id',ids).in('status',['in_progress','locked']);if(active.error)throw active.error;if(active.count)return out(req,{error:`Còn ${active.count} bài đang làm/bị khóa. Hãy xử lý trước khi đóng kỳ thi.`},409);const ready=await db.from('exam_attempts').select('id').in('session_id',ids).eq('status','ready');if(ready.error)throw ready.error;const rids=(ready.data||[]).map(x=>x.id);if(rids.length){const exp=await db.from('exam_attempts').update({status:'expired'}).in('id',rids);if(exp.error)throw exp.error;const rev=await db.from('attempt_sessions').update({revoked_at:new Date().toISOString()}).in('attempt_id',rids).is('revoked_at',null);if(rev.error)throw rev.error;}const sc=await db.from('exam_sessions').update({status:'closed'}).in('id',ids);if(sc.error)throw sc.error;}}
  if(target==='ready'){const s=await db.from('exam_sessions').update({status:'ready'}).eq('exam_id',examId);if(s.error)throw s.error;}
  if(target==='live'){const s=await db.from('exam_sessions').update({status:'live'}).eq('exam_id',examId);if(s.error)throw s.error;}
  if(target==='draft'){const s=await db.from('exam_sessions').update({status:'draft'}).eq('exam_id',examId);if(s.error)throw s.error;}
  const patch:any={status:target};if(target==='closed'&&!exam.retention_until)patch.retention_until=new Date(Date.now()+Number(exam.retention_days||30)*86400000).toISOString();if(['draft','ready','live'].includes(target))patch.retention_until=null;const up=await db.from('exams').update(patch).eq('id',examId).select().single();if(up.error)throw up.error;await audit(a.user.id,examId,current,target,{retentionUntil:up.data.retention_until});return out(req,{ok:true,exam:up.data});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,{error:'Method not allowed'},405);try{const b=await req.json().catch(()=>({}));if(b.action==='set-status')return setStatus(req,b);return out(req,{error:'Action không hợp lệ.'},400);}catch(e){console.error(e);const s=Number((e as any)?.status||500);return out(req,{error:s>=500?'Máy chủ đang gặp lỗi.':String((e as any)?.message||'Có lỗi xảy ra.')},s);}});
