import { createClient } from "jsr:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const enc=new TextEncoder();
const ORIGINS=new Set(['https://ai-clo-ptithcm.github.io','https://apmaths.github.io']);
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=ORIGINS.has(o)||o.startsWith('http://localhost:')||o.startsWith('http://127.0.0.1:');return {'Access-Control-Allow-Origin':ok?o:'https://ai-clo-ptithcm.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-exam-token','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(req)});}
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,{error:'Method not allowed'},405);try{const token=req.headers.get('x-exam-token')||'';if(!token)return out(req,{error:'Phiên thi không hợp lệ.'},401);const hash=await sha(token);const s=await db.from('attempt_sessions').select('attempt_id').eq('token_hash',hash).is('revoked_at',null).maybeSingle();if(s.error)throw s.error;if(!s.data)return out(req,{error:'Phiên thi đã hết hiệu lực.'},401);const a=await db.from('exam_attempts').select('id,status,exam_student_id').eq('id',s.data.attempt_id).single();if(a.error)throw a.error;const st=await db.from('exam_students').select('exam_id,session_id').eq('id',a.data.exam_student_id).single();if(st.error)throw st.error;const [ex,se]=await Promise.all([db.from('exams').select('status').eq('id',st.data.exam_id).single(),db.from('exam_sessions').select('starts_at,ends_at,status').eq('id',st.data.session_id).single()]);if(ex.error)throw ex.error;if(se.error)throw se.error;return out(req,{examStatus:ex.data.status,sessionStatus:se.data.status,startsAt:se.data.starts_at,endsAt:se.data.ends_at,attemptStatus:a.data.status,serverNow:new Date().toISOString(),canStart:ex.data.status==='live'&&Date.now()>=Date.parse(se.data.starts_at)&&Date.now()<Date.parse(se.data.ends_at)});}catch(e){console.error(e);return out(req,{error:'Không kiểm tra được trạng thái phòng thi.'},500);}});
