import { createClient } from "jsr:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const enc=new TextEncoder();
const ORIGINS=new Set(['https://ai-clo-ptithcm.github.io','https://apmaths.github.io']);

function cors(req:Request){const o=req.headers.get('origin')||'';const ok=ORIGINS.has(o)||o.startsWith('http://localhost:')||o.startsWith('http://127.0.0.1:');return {'Access-Control-Allow-Origin':ok?o:'https://ai-clo-ptithcm.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function out(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)});}
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function clean(v:any){return String(v??'').trim();}
function makeCode(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const a=new Uint8Array(8);crypto.getRandomValues(a);const s=[...a].map(x=>alphabet[x%alphabet.length]).join('');return `${s.slice(0,4)}-${s.slice(4)}`;}

async function actor(req:Request){const auth=req.headers.get('authorization')||'';const jwt=auth.replace(/^Bearer\s+/i,'');if(!jwt)throw Object.assign(new Error('Chưa đăng nhập.'),{status:401});const {data,error}=await db.auth.getUser(jwt);if(error||!data.user)throw Object.assign(new Error('Phiên đăng nhập không hợp lệ.'),{status:401});const {data:p,error:pe}=await db.from('profiles').select('*').eq('id',data.user.id).maybeSingle();if(pe)throw pe;if(!p?.active)throw Object.assign(new Error('Tài khoản chưa được kích hoạt.'),{status:403});return {user:data.user,profile:p};}
async function membership(a:any,examId:string){if(a.profile.system_role==='admin')return {admin:true,exam_role:'owner',permissions:[]};const {data,error}=await db.from('exam_members').select('exam_role,permissions').eq('exam_id',examId).eq('user_id',a.user.id).maybeSingle();if(error)throw error;return data||null;}
function permissionScope(m:any,p:string){if(m?.admin||m?.exam_role==='owner'||(m?.permissions||[]).includes(p))return {all:true,sessionIds:[] as string[]};const prefix=`${p}@`;const sessionIds=[...new Set((m?.permissions||[]).filter((x:string)=>String(x).startsWith(prefix)).map((x:string)=>String(x).slice(prefix.length)).filter(Boolean))] as string[];return {all:false,sessionIds};}
function allowedSession(m:any,p:string,sessionId:string){const s=permissionScope(m,p);return s.all||s.sessionIds.includes(sessionId);}
async function examScope(req:Request,examId:string,permission:string){const a=await actor(req),m=await membership(a,examId);if(!m)throw Object.assign(new Error('Bạn không thuộc kỳ thi này.'),{status:403});const s=permissionScope(m,permission);if(!s.all&&!s.sessionIds.length)throw Object.assign(new Error('Bạn không có quyền thực hiện thao tác này.'),{status:403});return {a,m,scope:s};}
async function attemptScope(req:Request,attemptId:string){const a=await actor(req);const {data:attempt,error}=await db.from('exam_attempts').select('*').eq('id',attemptId).single();if(error)throw error;const {data:student,error:se}=await db.from('exam_students').select('*').eq('id',attempt.exam_student_id).single();if(se)throw se;const m=await membership(a,student.exam_id);if(m&&allowedSession(m,'manage_live',attempt.session_id))return {actor:a,attempt,student};const {data:rs}=await db.from('exam_room_staff').select('id').eq('room_id',attempt.room_id).eq('user_id',a.user.id).maybeSingle();if(!rs)throw Object.assign(new Error('Bạn không phụ trách ca/phòng thi này.'),{status:403});return {actor:a,attempt,student};}
async function audit(userId:string,examId:string,action:string,entityType:string,entityId:string,payload:any={}){await db.from('audit_logs').insert({actor_user_id:userId,exam_id:examId,action,entity_type:entityType,entity_id:entityId,payload});}

async function importRoster(req:Request,b:any){const examId=String(b.examId||''),rows=Array.isArray(b.rows)?b.rows:[];if(!rows.length||rows.length>3000)return out(req,{error:'Danh sách phải có từ 1 đến 3000 sinh viên.'},400);const access=await examScope(req,examId,'manage_roster');const sessionIds=[...new Set(rows.map((r:any)=>String(r.sessionId||'')))];if(!access.scope.all&&sessionIds.some(id=>!access.scope.sessionIds.includes(id)))return out(req,{error:'Danh sách có sinh viên nằm ngoài ca được phân công.'},403);const roomIds=[...new Set(rows.map((r:any)=>String(r.roomId||'')))];const {data:sessions,error:se}=await db.from('exam_sessions').select('id,exam_id').in('id',sessionIds);if(se)throw se;if((sessions||[]).some(x=>x.exam_id!==examId)||sessions?.length!==sessionIds.length)return out(req,{error:'Có ca thi không thuộc kỳ thi.'},400);const {data:rooms,error:re}=await db.from('exam_rooms').select('id,session_id').in('id',roomIds);if(re)throw re;const roomMap=new Map((rooms||[]).map(x=>[x.id,x]));const newCodes:any[]=[];let created=0,updated=0;for(const r of rows){const studentCode=clean(r.studentCode).toUpperCase(),fullName=clean(r.fullName),className=clean(r.className)||null,sessionId=String(r.sessionId||''),roomId=String(r.roomId||'');if(!studentCode||!fullName||roomMap.get(roomId)?.session_id!==sessionId)return out(req,{error:`Dữ liệu không hợp lệ tại MSSV ${studentCode||'(trống)'}.`},400);const {data:existing,error:ee}=await db.from('exam_students').select('*').eq('exam_id',examId).eq('student_code',studentCode).maybeSingle();if(ee)throw ee;if(existing&&!access.scope.all&&!access.scope.sessionIds.includes(existing.session_id))return out(req,{error:`MSSV ${studentCode} đang thuộc ca ngoài phạm vi của bạn.`},403);let student=existing;if(existing){const u=await db.from('exam_students').update({full_name:fullName,class_name:className,session_id:sessionId,room_id:roomId,active:true}).eq('id',existing.id).select().single();if(u.error)throw u.error;student=u.data;updated++;}else{const ins=await db.from('exam_students').insert({exam_id:examId,session_id:sessionId,room_id:roomId,student_code:studentCode,full_name:fullName,class_name:className}).select().single();if(ins.error)throw ins.error;student=ins.data;created++;}const {data:codeRow}=await db.from('exam_student_codes').select('exam_student_id').eq('exam_student_id',student.id).maybeSingle();if(!codeRow){const code=makeCode();const ci=await db.from('exam_student_codes').insert({exam_student_id:student.id,code_hash:await sha(code)});if(ci.error)throw ci.error;newCodes.push({studentId:student.id,studentCode,fullName,className,accessCode:code,sessionId,roomId});}}
await audit(access.a.user.id,examId,'roster_import','exam',examId,{created,updated,newCodes:newCodes.length,total:rows.length,scope:access.scope.all?'all':access.scope.sessionIds});return out(req,{ok:true,created,updated,newCodes});}

async function generateCodes(req:Request,b:any){const examId=String(b.examId||''),ids=Array.isArray(b.studentIds)?b.studentIds.map(String):[];const access=await examScope(req,examId,'manage_roster');let q=db.from('exam_students').select('*').eq('exam_id',examId).eq('active',true);if(ids.length)q=q.in('id',ids);if(!access.scope.all)q=q.in('session_id',access.scope.sessionIds);const {data:students,error}=await q;if(error)throw error;if(ids.length&&(students||[]).length!==ids.length)return out(req,{error:'Có sinh viên nằm ngoài ca được phân công.'},403);const codes=[];for(const s of students||[]){const code=makeCode();const {data:old}=await db.from('exam_student_codes').select('code_version').eq('exam_student_id',s.id).maybeSingle();const up=await db.from('exam_student_codes').upsert({exam_student_id:s.id,code_hash:await sha(code),code_issued_at:new Date().toISOString(),code_version:Number(old?.code_version||0)+1},{onConflict:'exam_student_id'});if(up.error)throw up.error;codes.push({studentId:s.id,studentCode:s.student_code,fullName:s.full_name,className:s.class_name,accessCode:code,sessionId:s.session_id,roomId:s.room_id});}await audit(access.a.user.id,examId,'access_codes_regenerated','exam',examId,{count:codes.length,scope:access.scope.all?'all':access.scope.sessionIds});return out(req,{ok:true,codes});}

async function transferDevice(req:Request,b:any){const attemptId=String(b.attemptId||'');const s=await attemptScope(req,attemptId);await db.from('attempt_sessions').update({revoked_at:new Date().toISOString()}).eq('attempt_id',attemptId).is('revoked_at',null);await db.from('attempt_events').insert({attempt_id:attemptId,event_type:'device_transfer_allowed',payload:{by:s.actor.user.id}});await audit(s.actor.user.id,s.student.exam_id,'device_transfer','attempt',attemptId,{});return out(req,{ok:true});}
async function setLock(req:Request,b:any,unlock=false){const attemptId=String(b.attemptId||''),reason=clean(b.reason);const s=await attemptScope(req,attemptId);const patch=unlock?{status:'in_progress',locked_at:null,locked_reason:null}:{status:'locked',locked_at:new Date().toISOString(),locked_reason:reason||'Giám thị khóa bài'};const r=await db.from('exam_attempts').update(patch).eq('id',attemptId).select().single();if(r.error)throw r.error;await db.from('attempt_events').insert({attempt_id:attemptId,event_type:unlock?'unlocked_by_proctor':'locked_by_proctor',payload:{reason:reason||null}});await audit(s.actor.user.id,s.student.exam_id,unlock?'attempt_unlock':'attempt_lock','attempt',attemptId,{reason});return out(req,{ok:true,attempt:r.data});}
async function reopen(req:Request,b:any){const attemptId=String(b.attemptId||''),extra=Math.max(1,Math.min(180,Number(b.extraMinutes||5)));const s=await attemptScope(req,attemptId);const deadline=new Date(Date.now()+extra*60000).toISOString();const r=await db.from('exam_attempts').update({status:'in_progress',submitted_at:null,locked_at:null,locked_reason:null,deadline_at:deadline}).eq('id',attemptId).select().single();if(r.error)throw r.error;await db.from('attempt_sessions').update({revoked_at:new Date().toISOString()}).eq('attempt_id',attemptId).is('revoked_at',null);await db.from('attempt_events').insert({attempt_id:attemptId,event_type:'reopened',payload:{extraMinutes:extra}});await audit(s.actor.user.id,s.student.exam_id,'attempt_reopen','attempt',attemptId,{extraMinutes:extra});return out(req,{ok:true,deadlineAt:deadline});}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,{error:'Method not allowed'},405);try{const b=await req.json().catch(()=>({}));switch(String(b.action||'')){case'import-roster':return importRoster(req,b);case'generate-codes':return generateCodes(req,b);case'transfer-device':return transferDevice(req,b);case'lock-attempt':return setLock(req,b,false);case'unlock-attempt':return setLock(req,b,true);case'reopen-attempt':return reopen(req,b);default:return out(req,{error:'Action không hợp lệ.'},400);}}catch(e){console.error(e);const status=Number((e as any)?.status||500);return out(req,{error:status>=500?'Máy chủ đang gặp lỗi.':String((e as any)?.message||'Có lỗi xảy ra.')},status);}});