-- AI-CLO PTITHCM security hardening - 2026-09-18
-- Close direct-write paths around profiles and assessment grading while preserving RPC workflows.

-- 1) Prevent a non-admin user from escalating privileges or changing
-- admin-managed identity/lock fields on their own profile.
create or replace function public.guard_profile_sensitive_update()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if auth.uid() is not null
     and auth.uid() = old.id
     and coalesce(old.role, '') <> 'admin' then
    if new.id is distinct from old.id
       or new.role is distinct from old.role
       or new.is_active is distinct from old.is_active
       or new.locked_at is distinct from old.locked_at
       or new.locked_by is distinct from old.locked_by
       or new.email is distinct from old.email
       or new.mssv is distinct from old.mssv
       or new.created_at is distinct from old.created_at then
      raise exception using
        errcode = '42501',
        message = 'Không được tự thay đổi vai trò, trạng thái tài khoản hoặc thông tin định danh do hệ thống quản lý.';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.guard_profile_sensitive_update()
from public, anon, authenticated;

drop trigger if exists trg_guard_profile_sensitive_update on public.profiles;
create trigger trg_guard_profile_sensitive_update
before update on public.profiles
for each row
execute function public.guard_profile_sensitive_update();

-- 2) Exam attempts must be created through start_exam_attempt().
-- Students must never directly update score/submission/attempt metadata.
drop policy if exists exam_attempts_student_insert on public.exam_attempts;
drop policy if exists exam_attempts_own_update on public.exam_attempts;
drop policy if exists exam_attempts_staff_update on public.exam_attempts;

create policy exam_attempts_staff_update
on public.exam_attempts
for update
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.exams e
    where e.id = exam_attempts.exam_id
      and public.is_subject_teacher(e.subject_id)
  )
)
with check (
  public.is_admin()
  or exists (
    select 1
    from public.exams e
    where e.id = exam_attempts.exam_id
      and public.is_subject_teacher(e.subject_id)
  )
);

-- 3) Draft answers may only be changed through save_exam_progress(),
-- which enforces ownership, submitted state, valid option, question membership and time limit.
drop policy if exists attempt_draft_answers_own_insert on public.attempt_draft_answers;
drop policy if exists attempt_draft_answers_own_update on public.attempt_draft_answers;

-- 4) Final answers are server-generated by finalize_exam_attempt().
-- Remove all student direct-write paths so is_correct cannot be forged.
drop policy if exists student_answers_student_insert on public.student_answers;
drop policy if exists student_answers_own_update on public.student_answers;

-- 5) Sensitive assessment RPCs require an authenticated session.
revoke execute on function public.start_exam_attempt(uuid) from public, anon;
revoke execute on function public.save_exam_progress(uuid, uuid, text) from public, anon;
revoke execute on function public.submit_exam_attempt(uuid, jsonb) from public, anon;
revoke execute on function public.finalize_exam_attempt(uuid) from public, anon;
revoke execute on function public.get_attempt_result(uuid) from public, anon;
revoke execute on function public.get_exam_attempt_payload(uuid) from public, anon;
revoke execute on function public.populate_attempt_questions(uuid) from public, anon;

grant execute on function public.start_exam_attempt(uuid) to authenticated;
grant execute on function public.save_exam_progress(uuid, uuid, text) to authenticated;
grant execute on function public.submit_exam_attempt(uuid, jsonb) to authenticated;
grant execute on function public.finalize_exam_attempt(uuid) to authenticated;
grant execute on function public.get_attempt_result(uuid) to authenticated;
grant execute on function public.get_exam_attempt_payload(uuid) to authenticated;
grant execute on function public.populate_attempt_questions(uuid) to authenticated;
