import { createClient } from "jsr:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGINS=new Set(['https://ai-clo-ptithcm.github.io','https://apmaths.github.io']);
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=ORIGINS.has(o)||o.startsWith('http://localhost:')||o.startsWith('http://127.0.0.1:');return {'Access-Control-Allow-Origin':ok?o:'https://ai-clo-ptithcm.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(req)});}
async function admin(req:Request){const jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)throw Object.assign(new Error('Chưa đăng nhập.'),{status:401});const u=await db.auth.getUser(jwt);if(u.error||!u.data.user)throw Object.assign(new Error('Phiên đăng nhập không hợp lệ.'),{status:401});const p=await db.from('profiles').select('*').eq('id',u.data.user.id).maybeSingle();if(p.error)throw p.error;if(!p.data?.active||p.data.system_role!=='admin')throw Object.assign(new Error('Chỉ Admin hệ thống được xóa dữ liệu kỳ thi.'),{status:403});return {user:u.data.user,profile:p.data};}
async function exam(examId:string){const r=await db.from('exams').select('*').eq('id',examId).single();if(r.error)throw r.error;return r.data;}
async function stats(examId:string){const students=await db.from('exam_students').select('id',{count:'exact'}).eq('exam_id',examId);if(students.error)throw students.error;const ids=(students.data||[]).map(x=>x.id);const attempts=ids.length?await db.from('exam_attempts').select('id,status',{count:'exact'}).in('exam_student_id',ids):{data:[],count:0,error:null} as any;if(attempts.error)throw attempts.error;const attemptIds=(attempts.data||[]).map((x:any)=>x.id);const q=attemptIds.length?await db.from('attempt_questions').select('id',{count:'exact',head:true}).in('attempt_id',attemptIds):{count:0,error:null} as any;if(q.error)throw q.error;const ev=attemptIds.length?await db.from('attempt_events').select('id',{count:'exact',head:true}).in('attempt_id',attemptIds):{count:0,error:null} as any;if(ev.error)throw ev.error;const assets=await db.from('exam_assets').select('id,size_bytes,provider,bucket,object_path').eq('exam_id',examId).is('deleted_at',null);if(assets.error)throw assets.error;const papers=await db.from('exam_sessions').select('id').eq('exam_id',examId);if(papers.error)throw papers.error;const sessionIds=(papers.data||[]).map(x=>x.id);const paperCount=sessionIds.length?await db.from('exam_papers').select('id',{count:'exact',head:true}).in('session_id',sessionIds):{count:0,error:null} as any;return {students:students.count||0,attempts:attempts.count||0,attemptQuestions:q.count||0,events:ev.count||0,assets:(assets.data||[]).length,assetBytes:(assets.data||[]).reduce((n:number,x:any)=>n+Number(x.size_bytes||0),0),papers:paperCount.count||0,activeAttempts:(attempts.data||[]).filter((x:any)=>['in_progress','locked'].includes(x.status)).length,assetRows:assets.data||[]};}
async function preview(req:Request,b:any){await admin(req);const ex=await exam(String(b.examId||'')),s=await stats(ex.id);return out(req,{exam:{id:ex.id,code:ex.code,name:ex.name,status:ex.status,retentionUntil:ex.retention_until},...s,assetRows:undefined});}
async function purge(req:Request,b:any){const a=await admin(req),examId=String(b.examId||''),ex=await exam(examId);if(!['closed','archived'].includes(ex.status))return out(req,{error:'Chỉ xóa dữ liệu khi kỳ thi đã đóng hoặc lưu trữ.'},409);if(String(b.confirmCode||'').trim().toUpperCase()!==String(ex.code).trim().toUpperCase())return out(req,{error:'Mã xác nhận không khớp mã kỳ thi.'},400);if(b.archiveConfirmed!==true)return out(req,{error:'Phải xác nhận đã xuất/lưu hồ sơ cần thiết trước khi xóa.'},400);const s=await stats(examId);if(s.activeAttempts)return out(req,{error:`Còn ${s.activeAttempts} bài đang làm/bị khóa. Không thể xóa.`},409);
  const studentRows=await db.from('exam_students').select('id').eq('exam_id',examId);if(studentRows.error)throw studentRows.error;const studentIds=(studentRows.data||[]).map(x=>x.id);if(studentIds.length){const ar=await db.from('exam_attempts').select('id').in('exam_student_id',studentIds);if(ar.error)throw ar.error;const attemptIds=(ar.data||[]).map(x=>x.id);if(attemptIds.length){const del=await db.from('exam_attempts').delete().in('id',attemptIds);if(del.error)throw del.error;}const ds=await db.from('exam_students').delete().in('id',studentIds);if(ds.error)throw ds.error;}
  const sessions=await db.from('exam_sessions').select('id').eq('exam_id',examId);if(sessions.error)throw sessions.error;const sessionIds=(sessions.data||[]).map(x=>x.id);if(sessionIds.length){const dp=await db.from('exam_papers').delete().in('session_id',sessionIds);if(dp.error)throw dp.error;}
  for(const asset of s.assetRows){if(asset.provider==='supabase'){const rm=await db.storage.from(asset.bucket).remove([asset.object_path]);if(rm.error)throw rm.error;}}
  if(s.assetRows.length){const da=await db.from('exam_assets').delete().in('id',s.assetRows.map((x:any)=>x.id));if(da.error)throw da.error;}
  const now=new Date().toISOString();const up=await db.from('exams').update({status:'archived',retention_until:now}).eq('id',examId);if(up.error)throw up.error;await db.from('audit_logs').insert({actor_user_id:a.user.id,exam_id:examId,action:'exam_data_purged',entity_type:'exam',entity_id:examId,payload:{students:s.students,attempts:s.attempts,attemptQuestions:s.attemptQuestions,events:s.events,assets:s.assets,assetBytes:s.assetBytes,papers:s.papers}});return out(req,{ok:true,purged:{students:s.students,attempts:s.attempts,assets:s.assets,papers:s.papers}});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,{error:'Method not allowed'},405);try{const b=await req.json().catch(()=>({}));if(b.action==='preview')return preview(req,b);if(b.action==='purge')return purge(req,b);return out(req,{error:'Action không hợp lệ.'},400);}catch(e){console.error(e);const s=Number((e as any)?.status||500);return out(req,{error:s>=500?'Máy chủ đang gặp lỗi.':String((e as any)?.message||'Có lỗi xảy ra.')},s);}});
